# Generated by Django 4.2.2 on 2024-02-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicesapp', '0006_alter_checkout_address_alter_checkout_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
